### ISSUE TITLE
Is worked on mac os?

### ISSUE THREAD

**Issue by cndnhere** [thumbmarkjs/thumbmarkjs#21]
Recently, I used fingerprints to generate a unique device ID. In Windows it works, but in Mac OS it changes the deviceid after the next day when the system starts.

**Comment by ilkkapeltola** [comment]
It depends on the browser. I don't have a Mac so I'm not sure what it's doing.
What you could do to help figure it out is to store the JSON one day, then wait for it to change. Have both of the JSONs available and use the JSON diff tool to see where it changes.
I'm pretty sure this is a browser-specific anti-fingerprinting thing. If it affects only e.g. the canvas element, then I can disable that for Safari.

**Comment by cndnhere** [comment]
Thank for your response.
Today I checked the issue on Mac OS. It's working fine on Mac OS, but have one more issue.
I have around ten PCs in my lab with the same Windows operating system and the same hardware configuration. In all PCs, it generates the same unique ID on the same browser. 
Actually, I want to generate browser and system-specific unique ID.

**Comment by ilkkapeltola** [comment]
This approach unfortunately will not solve your need.
Identical hardware, identical software will generate same id's.
