### ISSUE TITLE
ECMAScript and UMD versions for library

### ISSUE THREAD

**Issue by le0pard** [thumbmarkjs/thumbmarkjs#22]
Thanks for amazing library. 

Right now testing it for pet project and find out, that package contain only `commonjs` version. Problem with this, that such version cannot be used with `ES6` projects - system just fail to `import` it. Will be good, if package will provide also `ES6` and `UMD` versions. 

I did such approach for my last library re2js - https://github.com/le0pard/re2js/blob/main/package.json and https://github.com/le0pard/re2js/blob/main/rollup.config.js#L27-L52

This allow to anyone use it with commonjs, es6 or udm from single package.

**Comment by ilkkapeltola** [comment]
Right, yeah. I'm exceptionally poor with these kind of things, but I'll figure it out!

**Comment by ilkkapeltola** [comment]
Could you check if what I did now works for you? I've published multiple formats with rollup:
IIFE (for browser): https://cdn.jsdelivr.net/npm/@thumbmarkjs/thumbmarkjs/dist/thumbmark.iife.js
UMD: https://cdn.jsdelivr.net/npm/@thumbmarkjs/thumbmarkjs/dist/thumbmark.umd.js
CommonJS: https://cdn.jsdelivr.net/npm/@thumbmarkjs/thumbmarkjs/dist/thumbmark.cjs.js
ESM: https://cdn.jsdelivr.net/npm/@thumbmarkjs/thumbmarkjs/dist/thumbmark.esm.js
AMD: https://cdn.jsdelivr.net/npm/@thumbmarkjs/thumbmarkjs/dist/thumbmark.amd.js

**Comment by le0pard** [comment]
Thanks, @ilkkapeltola 

I will check in several hours, when will reach computer.

About formats - you just need `esm`, `cjs` and `umd`. 

> umd – Universal Module Definition, works as amd, cjs and iife all in one

So `umd` cover `amd` and `iife`. 

Also will be good to add `exports` section in package.json :  https://github.com/le0pard/re2js/blob/6fe44bd68f101d6993de9a60eb220ae04f334fbd/package.json#L26

BTW, `unpkg` key in package.json can be used for `umd` package : https://github.com/le0pard/re2js/blob/6fe44bd68f101d6993de9a60eb220ae04f334fbd/package.json#L25

**Comment by ilkkapeltola** [comment]
Thanks for the tips. Yeah, I was wondering if it's better to just provide umd and not the iife and amd separately at all. It doesn't seem to add too many bytes. Maybe for simplicity I'll do it that way. I'll look into the exports and unpkg too in a moment.

**Comment by le0pard** [comment]
Checked. ESM and CJS version works without issues:

```js
const { getFingerprint } = require('@thumbmarkjs/thumbmarkjs');

(async () => {
  const data = await getFingerprint()
  console.log(data)
})()
```

and

```js
import { getFingerprint } from '@thumbmarkjs/thumbmarkjs'

(async () => {
  const data = await getFingerprint()
  console.log(data)
})()
```

both output `12arglk`, so it works
