### ISSUE TITLE
WebGL throws errors when Brave is aggressively blocking fingerprinting

### ISSUE THREAD

**Issue by Joe12387** [thumbmarkjs/thumbmarkjs#28]
Hi.

Brave appears to not work with WebGL when it is set to "Aggressively block fingerprinting", causing the WebGL fingerprint to be set to "unsupported" even though WebGL is supported in Brave.

`Error: Vertex shader compilation failed: null
    at webgl.ts:73:17
    at webgl.ts:25:71
    at Function.from (<anonymous>)
    at webgl.ts:25:43
    at tslib.es6.js:147:23
    at Object.next (tslib.es6.js:128:53)
    at tslib.es6.js:121:71
    at new Promise (<anonymous>)
    at n (tslib.es6.js:117:12)
    at webgl.ts:17:1`

This seems to be because Brave returns `null` for `gl.getShaderParameter(vertexShader, gl.COMPILE_STATUS)`. I'm not sure if this is something that can be addressed or not, but you can at least detect if Brave is in strict mode similar to how [CreepJS does it](https://github.com/abrahamjuliot/creepjs/blob/552101f181398c4814c5db2e2dd7444c1bb2130d/src/utils/helpers.ts#L31).

Thanks!

**Comment by ilkkapeltola** [comment]
I'm confident something can be done about this. Thanks for bringing this to my attention.
I'll look into this soon.

**Comment by ilkkapeltola** [comment]
Looks like the new version doesn't have that problem.

**Comment by ilkkapeltola** [comment]
@Joe12387 please re-open if the error is still there.
