### ISSUE TITLE
Does the fingerprint changes if a user uninstall an extension or changes the display screen?

### ISSUE THREAD

**Issue by elieobeid7** [thumbmarkjs/thumbmarkjs#29]
We're using this tool to identify users internally and see which user did what and save their activities. 

If a user uninstalls an extension or changes the display screen or changes the font, would the signature change? I'm asking because if that's the case then I need another metric to track users by.

And is the fingerprint unique per user per browser? Or can two users with similar browsers have the same fingerprint?

**Comment by Joe12387** [comment]
Hi.

This is a great project, but as with any fingerprinting script it has limitations. Even proprietary services cannot track 100% of browsers uniquely these days. There will be cases where two users have the same fingerprint and there will be cases where the fingerprint will change, usually when a browser is updated causing the browser to behave differently. This project does not use the screen resolution or use font detection, but eventually as browsers continue to update, the signature will change. You'll likely see the most collisions (users with the same fingerprint) on Safari.

Thanks.

**Comment by elieobeid7** [comment]
oooooohhhhh nooooooooooo!! 99% of the users are safari users!  i need to use another  tracker then 😄 The internal tool I'm working on is used by video editors and video editors use safari :)  it's in production now!

Oh well! it's time to find some other tracker!

If it wasn't for this sentence, I would have continued to use it

> You'll likely see the most collisions (users with the same fingerprint) on Safari.

Thank you so much for this project though, love it, and love how straightforward it is to use.

**Comment by Joe12387** [comment]
Unfortunately you're probably not going to be able to find any open source projects that can accurately and uniquely track Safari users. The best you're going to get is using a proprietary service like fingerprint.com which I believe costs $500/mo at minimum and may still not do what you want it to do. Safari is definitely the most difficult browser to fingerprint, even more so than Brave.

**Comment by ilkkapeltola** [comment]
One correction, there is font detection, but quite true, Safari is a tough cookie:
- lots of identical devices
- people using exactly the same browser
- very default settings

If @elieobeid7 you come across a tracker that does well on Safari, let me know and I'll look into what they might be doing differently.

However, if your use case is internal, then are they logged into something? Can you detect their identity somehow?
If that's not possible, is all their activity under the same domain? You could use a cookie approach.

I don't think fingerprinting is an appropriate approach for internal things tbh. There's likely a more suitable approach with identities or cookies.

**Comment by elieobeid7** [comment]
@ilkkapeltola yes it's an internal tool that video editors use, there's one master account for everyone, I didn't bother create individual accounts for each user. 

I just need a tracker to save the progress, I use it as an identifier on AWS S3. Let's say you''re editing a video but you want to go home and continue tomorrow, you hit save, I save your browser fingerprint as an aws bucket fingerprint/yourvideo.mp4

next day I check your browser fingerprint and I use that to pull the video you saved from s3.


I don't know why I didn't use cookies :) I thought this is a better way in case a user deleted cookies by mistake, will revert back to cookies
