### ISSUE TITLE
Thank you for making our website much faster :)

### ISSUE THREAD

**Issue by elieobeid7** [thumbmarkjs/thumbmarkjs#34]
I'll close this issue immediately after I post it, hoping you see it :) It's not an issue, it's a funny story.

Today I was bored so I decided to check what I could improve in our internal web app, but I wasn't in the mood to code, it's a Sunday!

So I checked and I've seen that our internal tool uses cdnjs and jsdelivr and unpkg cdn, so I figured I'd make a small change and use one CDN provider instead, so that we don't have to call 3 different companies. 

Now I hate using unpkg, because it's the new kid on the block, I don't know how big their CDN network is. So I decided to use CDNJS instead even though I knew very well that it's the slowest CDN network out there, I've been using them since 2011, but Cloudflare is a well-known company so let's go with it. 

I changed everything, and I got to the last change which is thumbmarkjs, I couldn't find it on CDNJS, I could remove it, after all, [I don't need it](https://github.com/thumbmarkjs/thumbmarkjs/issues/29) for this project, but that would require writing some code to generate cookies, and it's a Sunday, I don't feel like coding today, besides if it ain't broke don't fix it.

So I ended up, redoing the exercise and I changed all the CDN URLs to JSDeliver just to match thumbmarkjs, and I kid you not, the website now is much much much faster. All that just because you didn't publish your library on any alternative CDN provider. I didn't run any benchmarks though, because it's Sunday :)  And btw, I have a 1GB/s fiber optics internet connection, I'm in Dubai and I felt the difference.

**Comment by ilkkapeltola** [comment]
Thank you @elieobeid7 😊 Nice story, loved it. Happy accidents I suppose!
