### ISSUE TITLE
permissions timeout

### ISSUE THREAD

**Issue by DanieleMancini** [thumbmarkjs/thumbmarkjs#37]
sometimes from one of my android devices  i get permissions:{timeout: true},
don't know if the cause is the device itself or my implementation,

the device is oneplus 8t using chrome 122, android 14.

**Comment by ilkkapeltola** [comment]
What would be a good solution to this in your opinion?
I don't know if there is a way to 'fix' this so it just doesn't time out.

I could parameterize the timeout value, which I think currently is 1 second.
But 1 second should be plenty for this already, so I'm not sure if it would solve it.

You can disable permissions if this is a concern for you.

**Comment by DanieleMancini** [comment]
i'm currently trying to figure out why only this device get permissions timeout, also i forked this repo and changed getFingerprint to getFingerprint(includeData?: boolean)  since i need the hash and the data toghether,
i will probably update you soon.

**Comment by ilkkapeltola** [comment]
I've thought about doing this too. I think I could expand the getFingerprintData to include the hash, which it currently does not.
