### ISSUE TITLE
prefers-color-scheme is not persistent on macOS and maybe other platforms

### ISSUE THREAD

**Issue by Joe12387** [thumbmarkjs/thumbmarkjs#38]
Hi.

On macOS, `prefers-color-scheme` changes between `light` and `dark` based on the time of day and applicable settings. This results in two different fingerprint depending on the time of day the script is run. This may also affect other platforms. I'm not really sure how to handle this other than removing `prefers-color-scheme` from the checked media features.

Thanks!

**Comment by ilkkapeltola** [comment]
Will remove.

**Comment by ilkkapeltola** [comment]
Removed `prefers-color-schemes` from media queries in 0.14.5

**Comment by ilkkapeltola** [comment]
Please re-open if the problem persists.
