### ISSUE TITLE
Developing Kotlin & Swift library

### ISSUE THREAD

**Issue by bstillitano** [thumbmarkjs/thumbmarkjs#42]
We're interested in porting this library over to Kotlin & Swift for native apps.

We'd like to gauge the interest in this space and would also like to ascertain whether or not thumbmarkjs would be interested in allowing our company to have a "sponsored" banner on the repo once it goes live?

**Comment by ilkkapeltola** [comment]
Just making sure I understand you right :)
You'd like to create repositories for Thumbmark in Kotlin and Swift in the thumbmarkjs' GitHub organization.
You'd port the logic in thumbmarkjs to Kotlin and Swift.
And you'd like if those repos had a 'sponsored' banner to your company?
That sounds like a good idea, by all means, let's do that.
Although, what's the company? I don't want to show support to just anything 😬 
Should the repos be called `thumbmark-kotlin` and `thumbmark-swift`?

**Comment by bstillitano** [comment]
Hey @ilkkapeltola thanks for getting back to me. That's correct. 

The company is "Ordermentum". A startup based in Sydney, AU. It's a software that facilitates the relationship between wholesale food and beverage suppliers and their customers across Australia.

**Comment by ilkkapeltola** [comment]
Sounds great!
I've created the two repos and invited you as a maintainer in case you decide to go forward with this.
Let me know if you get a change of hearts or something and I'll clean them out. But no stress about anything.

As you have full maintenance ownership, you're free to populate the readme as you wish, too.

**Comment by bstillitano** [comment]
Thanks mate, will pick this up when time allows next week.

**Comment by bstillitano** [comment]
> @bstillitano how about https://github.com/fingerprintjs/fingerprintjs-android and https://github.com/fingerprintjs/fingerprintjs-ios?
> Both MIT licensed, completely free to use, excellent quality, tested in thousands of Android and iOS apps and actively maintained by a dedicated engineering team.

No one is stopping you from using them...

They are also not free (open source does not equal free). See licensing here https://github.com/fingerprintjs/fingerprintjs/blob/master/docs/licensing.md. Any revenue generating platform that uses the library must pay a fee. 

You'll also notice that the library you've linked to did not support SPM at the time this one was developed and hadn't been updated in over 18 months.

YOU can make the choice of which ones YOU use. Feel free to use whichever one suits your business needs best 😄

**Comment by Valve** [comment]
@bstillitano sorry you used a wrong project and a wrong license link.
Here is a correct one for Android: https://github.com/fingerprintjs/fingerprintjs-android/blob/main/LICENSE
and for iOS: https://github.com/fingerprintjs/fingerprintjs-ios/blob/main/LICENSE
Both are MIT licensed and free.

> You should probably also disclose that you have a financial interest in the success and usage of those libraries.
This is not correct. Both projects are OSS and free to use.

**Comment by bstillitano** [comment]
Ok, but if I'm going to use the mobile SDKs I'm likely going to want to use the JS SDK which isn't free...

This is a free alternative for all platforms. No doubt your library is great and robust, but choice is also always a good thing for the end consumer.

As I've said, at the time this one was developed, the ones you've linked to were unmaintained and didn't support SPM. 

Wishing you all the successes for your future work with your library.
