### ISSUE TITLE
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER

### ISSUE THREAD

**Issue by i-santosh** [thumbmarkjs/thumbmarkjs#47]
function getVideoCard(): componentInterface | string {
  const canvas = document.createElement('canvas')
  const gl = canvas.getContext('webgl') ?? canvas.getContext('experimental-webgl')
    if (gl && 'getParameter' in gl) {
      ```const debugInfo = gl.getExtension("WEBGL_debug_renderer_info");```
      return {
        vendor: (gl.getParameter(gl.VENDOR) || '').toString(),
        vendorUnmasked: debugInfo ? (gl.getParameter(debugInfo.UNMASKED_VENDOR_WEBGL) || '').toString() : '',
        renderer: (gl.getParameter(gl.RENDERER) || '').toString(),
        rendererUnmasked: debugInfo ? (gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL) || '').toString() : '',
        version: (gl.getParameter(gl.VERSION) || '').toString(),
        shadingLanguageVersion: (gl.getParameter(gl.SHADING_LANGUAGE_VERSION) || '').toString(),
    }
  }
  return "undefined"
}

while using thumbmarkjs, Firefox is giving warning ```WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER```

**Comment by Joe12387** [comment]
Hi.

This warning has been present in Firefox for years. `WEBGL_debug_renderer_info` provides very useful data for fingerprinting, and until Mozilla actually removes this feature, it can safely be ignored in my opinion. However, given the code you've pasted, I would suggest wrapping the `debugInfo` declaration in a try catch in case Firefox or another browser removes this feature in the future.

Thanks.

**Comment by ilkkapeltola** [comment]
Yeah good point. I'll do this at some point.

**Comment by ilkkapeltola** [comment]
Would this be ok?

https://github.com/thumbmarkjs/thumbmarkjs/pull/65
