### ISSUE TITLE
bug: flickering scrollbar

### ISSUE THREAD

**Issue by dev-aly3n** [thumbmarkjs/thumbmarkjs#48]
Hi
We are using the Next.js example in our app, and there is a flickering scrollbar in the first render.
This library creates a blank iframe with the display set to block with important annotation. `("display","block","important")`
So, this block-iframe always causes overflow and shows the scrollbar for a moment and then disappears.

**Comment by ArianHamdi** [comment]
Maybe using ‍‍‍‍‍`position: absolute | fixed` can fix it, plus `opacity: 0` because I can still see the border."

**Comment by dev-aly3n** [comment]
hey guys. thanks for the update. but could you also publish this change to npm? @ilkkapeltola

**Comment by ilkkapeltola** [comment]
Doing this now :) sorry about the delay

**Comment by ilkkapeltola** [comment]
Done @dev-aly3n
