### ISSUE TITLE
Add note in "thumbmarkjs" redirecting developers to "@thumbmarkjs/thumbmarkjs"

### ISSUE THREAD

**Issue by mackenzie-grimes-noaa** [thumbmarkjs/thumbmarkjs#55]
I really like this library: it's lightweight, fast, and very helpful to distinguish between different users! I've found it to be the most complete and simple open-source option.

We're experimenting with using it so users can have our React.JS app open in multiple windows and/or displays. Our app uses websockets to create a session, but how to detect that two windows (cross-origin) are being viewed by the same user/machine so that we can sync data between the two windows?

thumbmarkjs has been a perfect solution for this, and gives us enough uniqueness until we (someday) implement something heavier like user accounts and logins.

### Suggestion
One suggestion I have is to update [the README of the NPM package](https://www.npmjs.com/package/thumbmarkjs) to make sure developers know to use [@thumbmarkjs/thumbmarkjs](https://www.npmjs.com/package/@thumbmarkjs/thumbmarkjs) (instead of [thumbmarkjs](https://www.npmjs.com/package/thumbmarkjs)) for any new applications to get the latest version of this library.

I installed the old `thumbmarkjs` in my app and then spent some time being frustrated/confused when newer features (such as `setOptions()`) weren't working as expected in my app. 

I finally found the note in the current README warning that `v0.12.1` was the last version pushed to `thumbmarkjs`, installed `@thumbmarkjs/thumbmarkjs`, and since then have had no issues. Still, it might help future developers to make this more prominent, perhaps near the top of the old `thumbmarkjs` package README with a link to the newer package, or [marking the NPM package as deprecated](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions).

I would offer a Pull Request for this, but I'm not sure how this library is being published to NPM and couldn't find any branch or CI/CD tracking the old `thumbmarkjs`.

**Comment by ilkkapeltola** [comment]
Fair point. I'll do that. I have been planning to but just have forgotten.

**Comment by ilkkapeltola** [comment]
Done

**Comment by ilkkapeltola** [comment]
Done
