### ISSUE TITLE
Audio not working on on Firefox 126.0.1

### ISSUE THREAD

**Issue by zeebz** [thumbmarkjs/thumbmarkjs#56]
It doesn't work on Firefox with version 126.0.1.
Excluding audio makes it work.

> Error creating audio fingerprint: TypeError: undefined is not a constructor

**Comment by ilkkapeltola** [comment]
Thanks. I'll look into this when I get to my vacations 😄

**Comment by ilkkapeltola** [comment]
Could not reproduce.
