### ISSUE TITLE
If you open inspect element with mobile view, hash will get changed

### ISSUE THREAD

**Issue by sohamnandi77** [thumbmarkjs/thumbmarkjs#59]

**Comment by ilkkapeltola** [comment]
Please add more details. I'm not sure I understand.

Also, if you could take a copy of the JSON object before-and-after, that would be good info.

**Comment by ilkkapeltola** [comment]
If I understand correctly, this changes probably the browser user agent or some or another.
I'd say expected behavior. Please re-open if you think this should not be the case.
