### ISSUE TITLE
ThumbmarkJS Collisions

### ISSUE THREAD

**Issue by anis-byanjankar** [thumbmarkjs/thumbmarkjs#60]
Do we have any testing results on fingerprint collisions ? i.e., two different devices with the same software and hardware with the same fingerprint. If yes, What is the probability of having such a collision?  Has anyone faced such issues?

**Comment by Joe12387** [comment]
Hi.

It depends on the browser:
 - Chromium: will probably be rather unique, but browser updates & changing settings will result in a different ID.
 - Firefox: less fingerprint-able than Chromium, but given its low marketshare it may still be okay for small amounts of traffic.
 - Safari: No chance. You'll likely only get a couple possible fingerprints. Apple is serious about containing tracking.

ThumbmarkJS seems to favor stability and persistence, so it tends to collide a lot versus say CreepJS.

This is a self plug (sorry!) but I'm working on a project to address these issues and currently have a prototype API that seemingly works very well on Chromium. Safari remains elusive, at least for now.

You can look at testing the API for free for now: https://overpoweredjs.com/

Again, sorry for the self plug. I require some traffic for study and thought this may help someone.

**Comment by ilkkapeltola** [comment]
@Joe12387 no harm in a bit of self-promotion :)

I've been thinking about extending this project with a back-end service for obvious reasons too, but the library gets 12 million hits per month right now, and I'm afraid making it _that good_ would also mean service costs.

Though, if the back-end was also an open-source component, perhaps people could host it themselves easily.

I'll close this issue, but I wouldn't mind linking to this project in the Readme.
