### ISSUE TITLE
Four digit Fingerprint

### ISSUE THREAD

**Issue by thes4s67** [thumbmarkjs/thumbmarkjs#61]
I just updated Chrome and my fingerprint is a 4 digit number. Is this safe and unique to use as an actual fingerprint? Before I would get 7 alphanumeric chars.

**Comment by Joe12387** [comment]
The script hashes the fingerprint object with murmurhash 3, then turns the hash (an integer) into base 36 (alphanumeric). You likely just got really lucky getting a short base 36 number with no alphabetical letters.

**Comment by ilkkapeltola** [comment]
Nothing in fingerprinting is unique. Same features will get same hash.
And some odd occasions I suppose different ones too, but that would be quite rare IMO.
