### ISSUE TITLE
0.16.0 should've been marked as a breaking chage

### ISSUE THREAD

**Issue by itamarbareket** [thumbmarkjs/thumbmarkjs#67]
In the recent 0.16.0 release, the hashing algorithm changed, this should be denoted as a major breaking change (e.g bump to 1.0.0)

**Comment by ilkkapeltola** [comment]
Hmm... how did it break? The hash string was variable length before. Please elabrate.
Perhaps you're right though, I did consider this.

**Comment by Joe12387** [comment]
I suppose it depends on what you mean by "breaking." I think OP might mean that the hash changed, but this library isn't really for long-term persistent identifiers. I wouldn't count this as breaking if this is what they mean.

**Comment by CharlesOkwuagwu** [comment]
@Joe12387 it means if you had systems that were relying on the thumbprint, then this change **`BREAKS`** those systems:

trying to store the thumbprint for example now breaks

`Error converting data type varchar to bigint.`

**Comment by ilkkapeltola** [comment]
Oh. I see. I didn't consider someone would want to store it as a bigint.

What's best, publish a fix in 0.15.x and then a new version for 1.0.0

... or just learn from this and leave it? :)

**Comment by ilkkapeltola** [comment]
I'm not sure which alternative the thumbs up was for, so I'll leave this open for now for further comments. 😁

**Comment by CharlesOkwuagwu** [comment]
> I'm not sure which alternative the thumbs up was for, so I'll leave this open for now for further comments. 😁

I Feel we should update our projects to use the variable length formats.

It takes the burden off you the maintainer.

Thanks again for this **FREE** solution to a real problem you are providing.

**Comment by ilkkapeltola** [comment]
>Thanks again for this FREE solution to a real problem you are providing.

No problem. Glad it's been found useful!
