### ISSUE TITLE
Question: Is there a way to retain the fingerprint between browsers?

### ISSUE THREAD

**Issue by ItayElgazar** [thumbmarkjs/thumbmarkjs#69]
Title says it all 👀

**Comment by ThingEngineer** [comment]
>between browsers

On the same machine?

If so you could use `setOption` to exclude fingerprint components that are browser specific leaving only machine specific components. Still this is a maybe and would depend on the browser API and how it returns results exactly. The smallest change in results for the same API call would throw this off.

If this does not work you would need to fork it get have more granular with the components and possibly adding new ones or normalize certain browser API return results to get a reliable "machine only" fingerprint from any browser on that machine.

You could check out hw-fingerprint if that is truly what you need.

**Comment by Valve** [comment]
@ItayElgazar even commercial products have a 30-40% match rate between different browsers on the same machine, it's a very challenging  task.
